Write-Host " BELOW IS POWERSHELL SCRIPT THAT WE USED TO PROMOTE A NEW FOREST / DOMAIN "

Intall-ADDSForest -DomainName "lab.local" -InstallDNS -Force

Write-Host " END OF THE FOREST / DOMAIN PROMOTION ON SERVER CORE "
